language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 3.7
matrix:
  fast_finish: true
dist: xenial
services:
  - xvfb
install:
  - pip install -r requirements.txt
  - buildout
  # - python bootstrap-buildout.py
  # - bin/buildout -N buildout:download-cache=downloads annotate
  # - bin/buildout -N buildout:download-cache=downloads
before_script:
- firefox -v
script:
  - code-analysis
  - test
after_success:
  - createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - brian.duncan@wildcardcorp.com
