# -*- coding: utf-8 -*-
from plone.app.registry.browser.controlpanel import ControlPanelFormWrapper
from plone.app.registry.browser.controlpanel import RegistryEditForm
from plone.z3cform import layout
from zope import schema
from zope.interface import Interface
from uwosh.oie.studyabroadstudent import _
from plone.namedfile import field
from plone.app.textfield import RichText
from plone.autoform.directives import widget
from plone.formwidget.namedfile.widget import NamedImageFieldWidget, NamedFileFieldWidget
from plone.supermodel import model


class IOIEStudyAbroadStudentControlPanel(Interface):

    model.fieldset(
        'Academic',
        fields=['majors', 'programs', 'subjects', 'credits', 'course_subject', 'enrollment_institution',
                'program_of_study', 'student_status', 'education_level', 'requirements_met',
                'course_subject_and_number', 'college_or_unit', 'sponsoring_unit_or_department', 'term', 'university',
                'title', 'building'],
    )
    model.fieldset(
        'Demographic',
        fields=['ethnicities', 'marriage_statuses','genders', 'immigration_status'],
    )
    model.fieldset(
        'Geography',
        fields=['countries', 'states_for_residency', 'us_states_territories', 'citizenship', 'language', ],
    )
    model.fieldset(
        'Housing',
        fields=['room_size', 'accommodation'],
    )
    model.fieldset(
        'Travel',
        fields=['airport', 'locations', 'airport_transfer', 'transition_type'],
    )
    model.fieldset(
        'Travel Documents',
        fields=['travel_document', 'visa_delivery_options']
    )
    model.fieldset(
        'Programs',
        fields=['eligibility_requirement', 'guest_lectures', 'equipment_and_space',
                'class_standing', 'approving_as', 'leadership_role', 'program_cycle', 'course_enrollment_at',
                'cooperating_partners', 'flyer', 'tuition_and_fees', 'provider_type', 'program_component',
                'program_type', ]
    )
    model.fieldset(
        'Compensation',
        fields=['percentage_or_lump_sum', 'compensation_payment_or_replacement', 'compensation_type',
                'salary_form_type', 'salary_terms', 'payment_forms']
    )
    model.fieldset(
        'OIE',
        fields=['oie_staff', 'session_hours', 'program_view_footer', 'uwo_logo', ]
    )
    model.fieldset(
        'Forms',
        fields=['state_of_wisconsin_need_based_travel_grant_form', 'special_student_form_for_undergraduate_admissions',
                'disciplinary_clearance_form']
    )

    majors = schema.Tuple(
        title=_(u'Majors'),
        default=(
            u'-- choose one --',
            u'Accounting',
            u'African American Studies',
            u'Anthropology',
            u'Art',
            u'Biology',
            u'Broadfield Natural Science',
            u'Broadfield Social Science',
            u'business-undeclared-prebus',
            u'Canada and U.S. Studies',
            u'Chemistry',
            u'Communication',
            u'Computer Science',
            u'Criminal Justice',
            u'Dual Early Childhood PK-3 and Special Education Birth through Age 8',
            u'Dual Elementary 1-6 and Special',
            u'emba',
            u'Earth Science',
            u'Economics',
            u'Education',
            u'Elementary Education',
            u'engineering-technology',
            u'English',
            u'English as a Second Language',
            u'Environmental Studies',
            u'Finance',
            u'Fine Arts',
            u'French',
            u'Geography',
            u'Geology',
            u'German',
            u'History',
            u'Human Resources',
            u'Human Services',
            u'Individually Planned',
            u'Interdisciplinary Studies',
            u'International Studies',
            u'japanese',
            u'Journalism',
            u'kinesiology',
            u'Liberal Arts',
            u'Liberal Studies',
            u'MBA',
            u'Management Information Systems (MIS)',
            u'Marketing',
            u'Mathematics',
            u'Medical Technology',
            u'Microbiology',
            u'Military Science',
            u'Music',
            u'Music Education',
            u'Music Therapy',
            u'Nursing',
            u'Operations Management',
            u'Philosophy',
            u'Physical Education',
            u'Physics',
            u'Political Science',
            u'Pre-Professional Studies',
            u'professional-counseling',
            u'Psychology',
            u'Public Affairs',
            u'Radio TV Film (RTF)',
            u'Religious Studies',
            u'Secondary Education',
            u'Social Work',
            u'Sociology',
            u'Spanish',
            u'Special Education Cross-Categorical',
            u'THEATRE ARTS',
            u'Urban and Regional Studies',
            u'Womens Studies',
            u'pre-engineering',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    programs = schema.Tuple(
        title=_(u'Programs'),
        default=(
            u'20th Century British Philosophy in Cambridge, UK',
            u'20th Century Eastern Europe and the Holocaust',
            u'3D Design, Art and Technology in Korea',
            u'Activism, Resistance, and Visual Rhetoric in Germany',
            u'American University of Rome, Italy (UW-Platteville)',
            u'American Writers in Paris',
            u'Animal Behavior Observation in Tanzania',
            u'Applied Parasitology in Nicaragua and Costa Rica',
            u'Applied Pharmacology',
            u'Approaches to Resource Management of Tropical Ecosystems in Belize',
            u'Asia-Pacific TEFL Workshop',
            u'AustraLearn - academic year',
            u'AustraLearn - semester',
            u'AustraLearn - short-term',
            u'Black Howler Monkey Research in Belize',
            u'British Politics and Political Thought',
            u'Business & Economics in China',
            u'Business & Economics in Peru',
            u'Business in Fulda, Germany',
            u'Business in India: Opportunities & Challenges (business participant)',
            u'Business in India: Opportunities & Challenges (student participants)',
            u'Camp Kyushu',
            u'Challenge Australia: Leadership Development',
            u'Challenge New Zealand: Leadership Development',
            u'Communication, Social Justice, Women and Gender Studies in Tanzania',
            u'Comparative Criminal Justice Systems in Great Britain & France',
            u'Coral Reefs and Geology of Bermuda',
            u'Counseling, Culture and Spirituality in India',
            u'Cross-Cultural Psychology Research in Brazil',
            u'Culture & Community Change in Costa Rica',
            u'Culture and Communication in Italy and Greece',
            u'Culture and Style in England and Italy',
            u'Czech Culture & Society in a Global Context',
            u'EMBA Abroad',
            u'Economics of the Carribean through Service Learning in Jamaica',
            u'Educators Abroad Student Teaching',
            u'Estonia, Russia and Eastern Europe in the 20th Century',
            u'Estudio de Lectoescritura en Costa Rica',
            u'Ethics & Community in Martha''s Vineyard, MA (USA)',
            u'European Business Travel Seminar',
            u'European Odyssey',
            u'Experience Scotland',
            u'Field Geology in China',
            u'Harbin Institute of Technology-Summer Program',
            u'Hessen - Frankfurt University of Applied Sciences - academic year',
            u'Hessen - Frankfurt University of Applied Sciences - semester',
            u'Hessen - Hochschule Darmstadt - academic year',
            u'Hessen - Hochschule Darmstadt - semester',
            u'Hessen - Hochschule Fulda - academic year',
            u'Hessen - Hochschule Fulda - semester',
            u'Hessen - Hochschule RheinMain - academic year',
            u'Hessen - Hochschule RheinMain - semester',
            u'Hessen - Hochschule für Gestaltung Offenbach am Main - academic year',
            u'Hessen - Hochschule für Gestaltung Offenbach am Main - semester',
            u'Hessen - Hochschule für Musik und Darstellende Kunst Frankfurt - academic year',
            u'Hessen - Hochschule für Musik und Darstellende Kunst Frankfurt - semester',
            u'Hessen - Johann Wolfgang Goethe-Universität Frankfurt - academic year',
            u'Hessen - Johann Wolfgang Goethe-Universität Frankfurt - semester',
            u'Hessen - Justus-Liebig-Universität Gießen - academic year',
            u'Hessen - Justus-Liebig-Universität Gießen - semester',
            u'Hessen - Philipps-Universität Marburg - IUSP',
            u'Hessen - Philipps-Universität Marburg - academic year',
            u'Hessen - Philipps-Universität Marburg - semester',
            u'Hessen - Technische Hochschule Mittelhessen - academic year',
            u'Hessen - Technische Hochschule Mittelhessen - semester',
            u'Hessen - Technische Universität Darmstadt - academic year',
            u'Hessen - Technische Universität Darmstadt - semester',
            u'Hessen - Universität Kassel - academic year',
            u'Hessen - Universität Kassel - semester',
            u'Hessen, Germany Student Exchange - academic year',
            u'Hessen, Germany Student Exchange - semester',
            u'History of British Philosophy in Cambridge, England',
            u'History of Styles',
            u'Hochschule Osnabrueck - academic year',
            u'Hochschule Osnabrueck - semester',
            u'Intensive Spanish in Salamanca, Spain - CAPP',
            u'Intensive Spanish in Salamanca, Spain - academic year',
            u'Intensive Spanish in Salamanca, Spain - semester',
            u'Intensive Spanish in Salamanca, Spain - short-term',
            u'International Operations Management in Ireland',
            u'International Summer University in Darmstadt, Germany',
            u'International Summer University in Frankfurt, Germany',
            u'International Summer University in Fulda, Germany',
            u'International Summer University in Giessen, Germany',
            u'International Summer University in Kassel, Germany',
            u'International Summer University in Marburg, Germany',
            u'International Winter University in Fulda, Germany',
            u'International Winter University in Kassel, Germany',
            u'Junior II Medical/Surgical Clinical in India',
            u'Kookmin Univeristy - Summer Language Program',
            u'Kookmin University - academic year',
            u'Kookmin University - semester',
            u'Language and Culture for Teachers (Costa Rica)',
            u'Languages Open Doors (Chile)',
            u'Leadership & Culture in Australia and New Zealand',
            u'Leadership & Culture in Australia',
            u'Lorenzo de'' Medici - Florence',
            u'Lorenzo de'' Medici - Rome',
            u'Lorenzo de'' Medici - Three Cities',
            u'Lorenzo de'' Medici - Tuscania',
            u'Los Angeles Connection (USA)',
            u'MBA Healthcare in India',
            u'MBA in China & Korea',
            u'Mathematics Education in China',
            u'Mathematics Education in Germany',
            u'Mathematics Education in Peru',
            u'Modern Democratic Politics in Europe',
            u'Modern European Politics and the Rise and Fall of European Facism',
            u'Nagasaki Junior College - semester',
            u'Nagasaki Junior College/USA Summer Camp Study & Internship Program',
            u'Nagasaki University of Foreign Studies, Japan (UW-Platteville academic year)',
            u'Nagasaki University of Foreign Studies, Japan (UW-Platteville semester)',
            u'National Student Exchange - academic year',
            u'National Student Exchange - semester',
            u'Nationalism and Internationalism in the Heart of Europe',
            u'Nicaragua: Gender, Poverty, and Activism',
            u'Ningbo University - academic year',
            u'Ningbo University - semester',
            u'Nursing Clinical Community & Families in Peru (Batch 1)',
            u'Nursing Clinical Community & Families in Peru (Batch 2)',
            u'Nursing Clinical Community and Families in Nicaragua',
            u'Nursing Clinical Rotations AND Nursing & Health Care in India (combined programs)',
            u'Nursing Clinical Rotations in Uganda',
            u'Nursing Community Health Clinical in India',
            u'Peruvian Business Travel Seminar in Lima',
            u'Politics and Political History in Great Britain',
            u'Quest III Literary Landscapes: Ireland',
            u'Quest III Migration, Culture, and Human Rights in the Americas in Nicaragua',
            u'Quest III in Panama',
            u'Quest III: Culture & Community Change in Costa Rica',
            u'Reading and Writing in Place: Ireland',
            u'Reason & Religion in 18th Century Scotland',
            u'Religious Studies in India & Nepal',
            u'Ritsumeikan Asia Pacific University Student Exchange - academic year',
            u'Ritsumeikan Asia Pacific University Student Exchange - semester',
            u'Seijo University Student Exchange (academic year)',
            u'Seijo University Student Exchange (semester)',
            u'Seminar on Globalization - Africas Experience in Kenya',
            u'Service-Learning in Malaysia',
            u'Social Work Study in Germany - Summer + Fall Semester',
            u'Social Work Study in Germany - Summer',
            u'Society and Culture in Greece & London',
            u'South Central University for Nationalities, China (UW-Platteville)',
            u'Spanish Language & Culture in Guanajuato, Mexico',
            u'Spanish and Economics Studies in Peru',
            u'Spanish-American Institute of International Education, Spain (UW-Platteville)',
            u'Spring Interim in Rome',
            u'St. Mary''s University College, England (academic year; UW-Platteville)',
            u'St. Mary''s University College, England (semester; UW-Platteville)',
            u'Student Consulting Practicum + European Business Travel Seminar',
            u'Student Consulting Practicum + Peruvian Business Travel Seminar',
            u'Student Consulting Practicum',
            u'Study in Lille, France',
            u'Study plus Intern or Teach in China',
            u'Study plus Intern or Volunteer in Australia',
            u'Summer Courses in Osnabrueck, Germany',
            u'Summer in England and Scotland',
            u'Survey of Special and Early Childhood Education in Belize',
            u'Sustainability & Globalization - Africas Experience in Uganda',
            u'THM Internship in Germany',
            u'Teach in China',
            u'Teacher Education in Korea',
            u'The Intern Group',
            u'The Jewish Question in European Politics in Poland and Germany',
            u'Travel Writing in Nicaragua',
            u'Travel and Documentary Photography in England',
            u'Traveling Through Literary and Artistic England',
            u'USA Summer Camp (Japan)',
            u'Universidad Bernardo O''Higgins Student Exchange (academic year)',
            u'Universidad Bernardo O''Higgins Student Exchange (semester)',
            u'Universidad Castilla-La Mancha (academic year)',
            u'Universidad del Pacifico Student Exchange - academic year',
            u'Universidad del Pacifico Student Exchange - semester',
            u'University Honors Program',
            u'University of Nagasaki Siebold - academic year',
            u'University of Nagasaki Siebold - semester',
            u'University of New Brunswick Student Exchange - academic year',
            u'University of New Brunswick Student Exchange - semester',
            u'University of Newcastle, Australia (UW-Platteville)',
            u'Viessmann Academy - Student Seminar in Sustainability in Germany',
            u'Viessmann Internship Program in Allendorf (summer)',
            u'Viessmann Internship Program in Schwandorf (summer)',
            u'Writing Across Cultures in Nicaragua',
            u'Youth Exchange Program in Japan',
            ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    subjects = schema.Tuple(
        title=_(u'Subjects'),
        default=(
            u'-- choose one --',
            u'AF AM ST',
            u'ANTHRO',
            u'ARABIC',
            u'ARAPAHO',
            u'ART',
            u'ASTRONY',
            u'BIOLOGY',
            u'BUSINESS',
            u'CHEM',
            u'COMM',
            u'COMP SCI',
            u'CRIM JUS',
            u'DFLL',
            u'ECON',
            u'ED FOUND',
            u'ED LDRSP',
            u'ELEM ED',
            u'eng-tech',
            u'ENGLISH',
            u'ENV STDS',
            u'EXT STDS',
            u'FL ELECT',
            u'FR ABRD',
            u'FRENCH',
            u'GEN ELEC',
            u'GEN STDS',
            u'GEOG',
            u'GEOLOGY',
            u'GERMAN',
            u'HEALTH',
            u'HISTORY',
            u'honors',
            u'HU ELECT',
            u'HUMAN SV',
            u'INTRDSCP',
            u'INTRNTL',
            u'JAPANESE',
            u'JOURNAL',
            u'KINESIOL',
            u'LIB SCI',
            u'LIB STDS',
            u'MATH',
            u'MED TECH',
            u'MIL SCI',
            u'MPA',
            u'MUSIC',
            u'NS ELECT',
            u'NURS-ACC',
            u'NURS-CNP',
            u'NURSING',
            u'PBIS',
            u'PHIL',
            u'PHYS AST',
            u'PHYS SCI',
            u'POLI SCI',
            u'PRAC ART',
            u'PROF COUNSELING',
            u'PRTGUESE',
            u'PSYCH',
            u'PUB ADM',
            u'PhysicalEducation',
            u'READING',
            u'RELSTDS',
            u'RUSSIAN',
            u'radio-tv-film',
            u'SEC ED',
            u'SHOSHONE',
            u'SOC WORK',
            u'social-justice',
            u'SOCIOLOGY',
            u'SPANISH',
            u'SPEC ED',
            u'SRVC CRS',
            u'SS ELECT',
            u'TBIS',
            u'THEATRE',
            u'URB REG',
            u'WOM STDS',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    ethnicities = schema.Tuple(
        title=_(u'Ethnicities'),
        default=(
            u'no answer',
            u'African-American',
            u'Hispanic',
            u'Native American',
            u'Asian/Pacific Islander',
            u'Other'
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    marriage_statuses = schema.Tuple(
        title=_(u'Marriage Statuses'),
        default=(u'Married', u'Single'),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    genders = schema.Tuple(
        title=_(u'Genders'),
        default=(u'Male', u'Female', u'Other'),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    states_for_residency = schema.Tuple(
        title=_(u'States for Residency'),
        default=(u'Wisconsin', u'Minnesota', u'Other'),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    us_states_territories = schema.Tuple(
        title=_(u'U.S. States and Territories'),
        default=(
            'Wisconsin',
            'Alaska',
            'Alabama',
            'Arkansas',
            'American Samoa',
            'Arizona',
            'California',
            'Colorado',
            'Connecticut',
            'District of Columbia',
            'Delaware',
            'Florida',
            'Georgia',
            'Guam',
            'Hawaii',
            'Iowa',
            'Idaho',
            'Illinois',
            'Indiana',
            'Kansas',
            'Kentucky',
            'Louisiana',
            'Massachusetts',
            'Maryland',
            'Maine',
            'Michigan',
            'Minnesota',
            'Missouri',
            'Northern Mariana Islands',
            'Mississippi',
            'Montana',
            'National',
            'North Carolina',
            'North Dakota',
            'Nebraska',
            'New Hampshire',
            'New Jersey',
            'New Mexico',
            'Nevada',
            'New York',
            'Ohio',
            'Oklahoma',
            'Oregon',
            'Pennsylvania',
            'Puerto Rico',
            'Rhode Island',
            'South Carolina',
            'South Dakota',
            'Tennessee',
            'Texas',
            'Utah',
            'Virginia',
            'Virgin Islands',
            'Vermont',
            'Washington',
            'West Virginia',
            'Wyoming',
            'none'
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    citizenship = schema.Tuple(
        title=_(u'Citizenship'),
        default=(u'U.S. Citizen', u'Permanent U.S. Resident', u'Other Citizenship'),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    session_hours = schema.Tuple(
        title=_(u'Session hours'),
        default=(u'09:00-11:00', u'15:00-17:00'),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    countries = schema.Tuple(
        title=_(u'Countries'),
        default=(
            'United States',
            'Abkhazia',
            'Afghanistan',
            'Akrotiri and Dhekelia',
            'Åland',
            'Albania',
            'Algeria',
            'American Samoa',
            'Angola',
            'Andorra',
            'Anguilla',
            'Antigua and Barbuda',
            'Argentina',
            'Armenia',
            'Aruba',
            'Australia',
            'Austria',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Bangladesh',
            'Barbados',
            'Belarus',
            'Belgium',
            'Belize',
            'Benin',
            'Bermuda',
            'Bhutan',
            'Bolivia',
            'Bosnia and Herzegovina',
            'Botswana',
            'Brazil',
            'British Virgin Islands',
            'Brunei',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Cape Verde',
            'Cayman Islands',
            'Central African Rep.',
            'Chad',
            'Channel Islands',
            'Chile',
            'China',
            'Christmas Island',
            'Cocos Island',
            'Colombia',
            'Comoros',
            'Congo, Dem. Rep.',
            'Congo, Rep.',
            'Cook Islands',
            'Costa Rica',
            'Cote d''Ivoire',
            'Croatia',
            'Cuba',
            'Cyprus',
            'Czech Rep.',
            'Czechoslovakia',
            'Denmark',
            'Djibouti',
            'Dominica',
            'Dominican Rep.',
            'East Germany',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guinea',
            'Eritrea',
            'Eritrea and Ethiopia',
            'Estonia',
            'Ethiopia',
            'Faeroe Islands',
            'Falkland Islands (Malvinas)',
            'Fiji',
            'Finland',
            'France',
            'French Guiana',
            'French Polynesia',
            'Gabon',
            'Gambia',
            'Georgia',
            'Germany',
            'Ghana',
            'Gibraltar',
            'Greece',
            'Greenland',
            'Grenada',
            'Guadeloupe',
            'Guam',
            'Guatemala',
            'Guernsey',
            'Guinea',
            'Guinea-Bissau',
            'Guyana',
            'Haiti',
            'Holy See',
            'Honduras',
            'Hong Kong, China',
            'Hungary',
            'Iceland',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Ireland',
            'Isle of Man',
            'Israel',
            'Italy',
            'Jamaica',
            'Japan',
            'Jersey',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Korea, Dem. Rep.',
            'Korea, Rep.',
            'Korea, United',
            'Kosovo',
            'Kuwait',
            'Kyrgyzstan',
            'Laos',
            'Latvia',
            'Lebanon',
            'Lesotho',
            'Liberia',
            'Libya',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Macao, China',
            'Macedonia, FYR',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives',
            'Mali',
            'Malta',
            'Marshall Islands',
            'Martinique',
            'Mauritania',
            'Mauritius',
            'Mayotte',
            'Mexico',
            'Micronesia, Fed. Sts.',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Montserrat',
            'Morocco',
            'Mozambique',
            'Myanmar',
            'Namibia',
            'Nauru',
            'Nepal',
            'Netherlands',
            'Netherlands Antilles',
            'New Caledonia',
            'New Zealand',
            'Ngorno-Karabakh',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'Niue',
            'Norfolk Island',
            'Northern Cyprus',
            'Northern Mariana Islands',
            'Norway',
            'Oman',
            'Pakistan',
            'Palau',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Pitcairn',
            'Poland',
            'Portugal',
            'Puerto Rico',
            'Qatar',
            'Reunion',
            'Romania',
            'Russia',
            'Rwanda',
            'Saint Barthelemy',
            'Saint Helena',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Martin',
            'Saint Vincent and the Grenadines',
            'Saint-Pierre-et-Miquelon',
            'Samoa',
            'San Marino',
            'Sao Tome and Principe',
            'Saudi Arabia',
            'Senegal',
            'Serbia',
            'Serbia and Montenegro',
            'Serbia excluding Kosovo',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Slovak Republic',
            'Slovenia',
            'Solomon Islands',
            'Somalia',
            'Somaliland',
            'South Africa',
            'South Ossetia',
            'Spain',
            'Sri Lanka',
            'Sudan',
            'Suriname',
            'Svalbard',
            'Swaziland',
            'Sweden',
            'Switzerland',
            'Syria',
            'Taiwan',
            'Tajikistan',
            'Tanzania',
            'Thailand',
            'Timor-Leste',
            'Togo',
            'Tokelau',
            'Tonga',
            'Transnistria',
            'Trinidad and Tobago',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Turks and Caicos Islands',
            'Tuvalu',
            'Uganda',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'Uruguay',
            'USSR',
            'Uzbekistan',
            'Wallis et Futuna',
            'Vanuatu',
            'Venezuela',
            'West Bank and Gaza',
            'West Germany',
            'Western Sahara',
            'Vietnam',
            'Virgin Islands (U.S.)',
            'Yemen Arab Republic (Former)',
            'Yemen Democratic (Former)',
            'Yemen, Rep.',
            'Yugoslavia',
            'Zambia',
            'Zimbabwe',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    program_type = schema.Tuple(
        title=_(u'Program Type'),
        default=(
            'Exchange-United States',
            'Exchange-International',
            'Group-Domestic with Leader',
            'Group-International with Leader',
            'Internship-United States',
            'Internship-International',
            'Study Abroad',
            'Study/Internship',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    program_component = schema.Tuple(
        title=_(u'Program Component'),
        default=(
            'Clinicals',
            'Field Research',
            'Internship',
            'Leadership',
            'Research',
            'Service Learning',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    accommodation = schema.Tuple(
        title=_(u'Accommodation'),
        default=(
            'Host Family',
            'Hostel',
            'Hotel',
            'International Student House',
            'Private Apartment',
            'Residence Hall',
            'Shared Apartment',
            'Rustic',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    room_size = schema.Tuple(
        title=_(u'Room Size'),
        default=(
            'Single Rooms',
            'Double Rooms',
            'Triple Rooms',
            'Multi-bed Rooms',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    locations = schema.Tuple(
        title=_(u'Locations'),
        default=(
            'UW Oshkosh Parking Lot 6; corner of Osceola & Pearl Ave.',
            'Chicago O''Hare International Airport',
            'Milwaukee General Mitchell Airport',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    airport = schema.Tuple(
        title=_(u'Airports'),
        default=(
            'Milwaukee',
            'Appleton',
            'O''Hare',
        ),
        value_type=schema.TextLine()
    )

    credits = schema.Tuple(
        title=_(u'Credits'),
        default=(
            '0',
            '1',
            '1.5',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            '11',
            '12',
            '13',
            '14',
            '15',
            '16',
            '17',
            '18',
            '19',
            '20',
            '21',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    travel_document = schema.Tuple(
        title=_(u'Travel Document'),
        default=(
            'Passport',
            'Driver''s License',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    provider_type = schema.Tuple(
        title=_(u'Provider Type'),
        default=(
            'Accommodation',
            'Air',
            'Entrance',
            'Government Agency',
            'High School',
            'Intensive Language School',
            'Other',
            'Religious Organization',
            'Transport',
            'Travel Agency-Educational',
            'Travel Agency-Logistics',
            'University',
            'Volunteer Organization',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    course_subject = schema.Tuple(
        title=_(u'Course Subject'),
        default=(
            'ACAD',
            'ACCT',
            'ANTHRO',
            'AF AM ST',
            'ARABIC',
            'ART',
            'BIOLOGY ',
            'ARAPAHO',
            'BUSINESS',
            'CHEM',
            'CHINESE',
            'CNSLR ED',
            'COMM ',
            'COMP SCI',
            'CRIM JUS ',
            'DFLL',
            'ECON',
            'ED FOUND',
            'ED LDRSP',
            'ELEM ED',
            'ENG TECH',
            'ENV STDS',
            'FERM',
            'FINANCE',
            'FRENCH',
            'GEOG',
            'GEOLOGY',
            'GERMAN',
            'HEALTH ED',
            'HISTORY',
            'HONORS',
            'HUMAN SV',
            'INFO SYS',
            'INTRDSCP',
            'INTRNT’L ',
            'JAPANESE',
            'JOURNAL',
            'KINESIOL',
            'LIB STDS',
            'MGMT & HR',
            'MARKETING',
            'MATH',
            'MED TECH ',
            'MIL SCI',
            'MPA',
            'MUSIC',
            'NUR-ACC',
            'NURS-CNP',
            'NURSING',
            'PHIL',
            'PHY/AST',
            'PHY ED',
            'PHYS SCI',
            'POL SCI',
            'PRAC ARTS ',
            'PBIS',
            'PSYCH',
            'PUB ADM',
            'RTF',
            'READING ',
            'RELSTDS',
            'RUSSIAN',
            'SOC',
            'SEC ED',
            'SOC JUSTICE',
            'SOC WORK',
            'SPANISH',
            'SPEC ED',
            'SRVC CRS',
            'SCM',
            'SMGT',
            'WBIS',
            'THEATRE',
            'USP',
            'URB/REG ',
            'WM STUD',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    tuition_and_fees = schema.Tuple(
        title=_(u'Tuition and Fees'),
        default=(
            '$0 Tuition; $0 Seg Fees',
            '$0 Tuition; $0 Seg Fees; relevant tuition equivalent to be charged',
            'No Change to Course Tuition & Fees',
            'Tuition Charged for 01 cr + related fees; charge outside of the tuition plateau',
            'Tuition Charged for 01 cr; Seg Fees Also Charged',
            'Tuition Charged for 02 cr; Seg Fees Also Charged',
            'Tuition Charged for 03 cr; $0 Seg Fees',
            'Tuition Charged for 03 cr + related fees; charge outside of the tuition plateau',
            'Tuition Charged for 03 cr; Seg Fees Also Charged',
            'Tuition Charged for 04 cr; Seg Fees Also Charged',
            'Tuition Charged for 05 cr; Seg Fees Also Charged',
            'Tuition Charged for 06 cr outside of the tuition plateau; $0 Seg Fees',
            'Tuition Charged for 06 cr; $0 Seg Fees',
            'Tuition Charged for 06 cr; Seg Fees Also Charged',
            'Tuition Charged for 07 cr; Seg Fees Also Charged',
            'Tuition Charged for 08 cr; Seg Fees Also Charged',
            'Tuition Charged for 09 cr; Seg Fees Also Charged',
            'Tuition Charged for 1.5 cr; Seg Fees Also Charged',
            'Tuition Charged for 10 cr; Seg Fees Also Charged',
            'Tuition Charged for 11 cr; Seg Fees Also Charged',
            'Tuition Charged for 12 cr; $0 Seg Fees',
            'Tuition Charged for 12 cr; Seg Fees Also Charged',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    flyer = schema.Tuple(
        title=_(u'Flyer'),
        default=(
            'Anthropology',
            'Art',
            'Australia & New Zealand',
            'Biology',
            'Canada',
            'China',
            'College of Education & Human Services',
            'College of Business',
            'Communication',
            'Computer Science',
            'College of Nursing',
            'Criminal Justice',
            'England/Scotland',
            'English',
            'Environmental Studies',
            'French/France',
            'General',
            'General for Admissions',
            'Geography',
            'Geology',
            'German',
            'Hessen (for external use only)',
            'History',
            'History & Political Science',
            'Honors',
            'Intern Abroad',
            'Italy',
            'Japan',
            'Journalism',
            'Liberal Studies',
            'Math',
            'National Student Exchange',
            'Non-UW Oshkosh Programs',
            'Philosophy',
            'Political Science',
            'Psychology',
            'Religious Studies',
            'S. Korea',
            'Scholarships',
            'Social Justice',
            'Social Work',
            'Spanish',
            'Teach',
            'Theatre',
            'USP',
            'Womens'' Studies',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    oie_staff = schema.Tuple(
        title=_(u'OIE Staff'),
        default=(
            'Application Intake Specialist',
            'Director',
            'English Language Support Coordinator',
            'Front-line Advisor',
            'Hessen Coordinator',
            'Immigration Compliance Coordinator',
            'International Financial Management Specialist',
            'NSE Coordinator',
            'Program Manager',
            'Study Abroad/Away Coordinator',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    payment_forms = schema.Tuple(
        title=_(u'Payment Forms'),
        default=(
            'Foundation',
            'PTF',
            'TTR',
            'DPR',
            'TER',
            'PIR',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    salary_terms = schema.Tuple(
        title=_(u'Salary Terms'),
        default=(
            'Overload 1.25%',
            'Overload 10%',
            'Overload 12.5%',
            'Overload 15%',
            'Overload 2.5%',
            'Overload 3.75%',
            'Overload 5%',
            'Overload 7.5%',
            'Overload Lump Sum',
            'Paid directly to Professor by Partner',
            'Part of Load/No Replacement',
            'Part of Load/Replacement',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    salary_form_type = schema.Tuple(
        title=_(u'Salary Form Type'),
        default=(
            'Payment to Individual Form (PTF) - Direct Payment',
            'Transaction Transfer Request (TTR) - Replacement Costs',
            'Foundation',
            'Not Applicable',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    visa_delivery_options = schema.Tuple(
        title=_(u'Visa Delivery Options'),
        default=(
            'OIE Mails',
            'OIE hand delivers',
            'Student applies in person',
            'Student Mails',
            'Travel Agency Secures',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    university = schema.Tuple(
        title=_(u'University'),
        default=(
            'UW-Oshkosh',
            'UW–Baraboo/Sauk County',
            'UW–Barron County',
            'UW-Colleges Online',
            'UW-Eau Claire',
            'UW–Fond du Lac',
            'UW–Fox Valley',
            'UW-Green Bay',
            'UW-La Crosse ',
            'UW-Madison',
            'UW–Manitowoc',
            'UW–Marathon County',
            'UW–Marinette',
            'UW–Marshfield/Wood County',
            'UW-Milwaukee ',
            'UW-Parkside ',
            'UW-Platteville ',
            'UW–Richland',
            'UW-River Falls',
            'UW–Rock County',
            'UW–Sheboygan',
            'UW-Stevens Point ',
            'UW-Stout',
            'UW-Superior',
            'UW–Washington County',
            'UW–Waukesha',
            'UW-Whitewater ',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    term = schema.Tuple(
        title=_(u'Term'),
        default=(
            '1 Fall Interim',
            '2 Spring Semester',
            '3 Spring Break',
            '4 Spring Interim',
            '5 Summer',
            '6 Fall Semester',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    sponsoring_unit_or_department = schema.Tuple(
        title=_(u'Sponsoring Unit or Department'),
        default=(
            'African American Studies',
            'Anthropology',
            'Applied Studies',
            'Art',
            'Biology',
            'Business, College of',
            'Canada & U.S. Studies',
            'Chemistry',
            'Communication Studies',
            'Computer Science',
            'Criminal Justice',
            'Economics',
            'Educational Leadership and Policy',
            'English',
            'Environmental Studies',
            'Foreign Languages and Literature',
            'Geography & Urban Planning',
            'Geology',
            'History',
            'Honors College',
            'Human Kinetics and Health Education  ',
            'Human Services Leadership',
            'Individually Planned Major',
            'Interactive Web Management',
            'Interdisciplinary Studies',
            'International Studies',
            'Journalism',
            'Kinesiology',
            'Letters and Science, College of',
            'Liberal Studies',
            'Literacy and Language',
            'Mathematics',
            'Mathematics Education',
            'Medical Technology',
            'Military Science',
            'Music',
            'Nursing, College of',
            'On-line & Continuing Education, Division of',
            'Philosophy',
            'Physics and Astronomy',
            'Political Science',
            'Pre-Professional Education',
            'Professional Counseling ',
            'Psychology',
            'Public Administration',
            'Quest I',
            'Quest II',
            'Quest III',
            'Radio-TV-Film',
            'Religious Studies',
            'Social Justice',
            'Social Work',
            'Sociology',
            'Special and Early Childhood Education',
            'Teaching and Learning',
            'Theatre',
            'University Studies Program',
            'Urban Planning',
            'Women''s and Gender Studies',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    college_or_unit = schema.Tuple(
        title=_(u'College or Unit'),
        default=(
            'B College of Business',
            'L College of Letters & Science',
            'N College of Nursing',
            'E College of Education & Human Services',
            'H Honors College',
            'C On-line & Continuing Education, Division of',
            'QI Quest I',
            'QII Quest II',
            'QIII Quest III',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    language = schema.Tuple(
        title=_(u'Language'),
        default=(
            'American Sign Language',
            'Arabic',
            'Chinese',
            'French',
            'German',
            'Italian',
            'Japanese',
            'Korean',
            'Russian',
            'Spanish',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    cooperating_partners = schema.Tuple(
        title=_(u'Cooperating Partners'),
        default=(
            'Academic Programs International (API)',
            'Accent International',
            'American Institute for Foreign Study (AIFS)',
            'AMIDEAST',
            'Amizade Ltd.',
            'Anglo Educational Services',
            'Anytour International',
            'Beyond Borders International / Minds Abroad',
            'Cultural Experiences Abroad (CEA)',
            'Customized Educational Programs Abroad (CEPA)',
            'China Sense',
            'Council on International Educational Exchange (CIEE)',
            'CISabroad',
            'Destination Partners',
            'Educators Abroad Ltd',
            'EF College Study Tours',
            'EIL Intercultural Learning',
            'Fellowship Travel',
            'Global Academic Ventures',
            'Global Engagement Institute',
            'Happy Tours - Peru',
            'Inspiration India',
            'International Studies Abroad (ISA)',
            'International Study Programs (ISP)',
            'International Volunteer HQ (IVHQ)',
            'Operation Groundswell',
            'Palace Travel',
            'Rama Tours',
            'Select Travel Study',
            'Seminars International',
            'Spanish Learning',
            'Vesna Tours',
            'VIDA Volunteer',
            'World Endeavors',
            'Worldstrides Capstone',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    course_subject_and_number = schema.Tuple(
        title=_(u'Course Subject & Number'),
        default=(
            'ANTHRO 362',
            'ANTHRO 394',
            'ART 306',
            'ART 308',
            'BIO 300',
            'BIO 360',
            'BIO 796',
            'BUS 341',
            'BUS 351',
            'BUS 365',
            'BUS 389',
            'BUS 411',
            'BUS 462',
            'BUS 486',
            'BUS 492',
            'BUS 494',
            'BUS 694',
            'BUS 740',
            'BUS 758',
            'BUS 792',
            'BUS 796',
            'CHEM 246',
            'CHEM 360',
            'COMM 213',
            'COMM 318',
            'COMM 400',
            'COMM 405',
            'CRIMINAL JUSTICE 375',
            'DFLL 230',
            'ECON 319',
            'ECON 320',
            'ECON 380',
            'ECON 386',
            'ECON 399',
            'ECON 409',
            'ECON 426',
            'ECON 427',
            'ED LDRSP 719',
            'ED LDRSP 796',
            'Elem Ed 202',
            'ELEM ED 349',
            'ELEM ED 377',
            'ELEM ED 400',
            'ELEM ED 401',
            'ELEM ED 404',
            'ELEM ED 405',
            'ELEM ED 406',
            'ELEM ED 424',
            'ELEM ED 453',
            'ELEM ED 454',
            'ELEM ED 455',
            'ELEM ED 496',
            'ELEM ED 577',
            'ENGLISH 204',
            'ENGLISH 205',
            'ENGLISH 211',
            'ENGLISH 212',
            'ENGLISH 220',
            'ENGLISH 224',
            'ENGLISH 225',
            'ENGLISH 226',
            'ENGLISH 247',
            'ENGLISH 294',
            'ENGLISH 302',
            'ENGLISH 305',
            'ENGLISH 306',
            'ENGLISH 316',
            'ENGLISH 318',
            'ENGLISH 332',
            'ENGLISH 347',
            'ENGLISH 350',
            'ENGLISH 353',
            'ENGLISH 356',
            'ENGLISH 357',
            'ENGLISH 370',
            'ENGLISH 396',
            'ENGLISH 405',
            'ENGLISH 505',
            'ENGLISH 506',
            'ENGLISH 547',
            'ENGLISH 550',
            'ENGLISH 553',
            'ENGLISH 556',
            'ENGLISH 557',
            'ENGLISH 570',
            'ENGLISH 596',
            'ENGLISH 605',
            'ENGLISH 709',
            'ENVT STDS 300',
            'ENVT STDS 390',
            'ENVT STDS 395',
            'EXT STDS 082',
            'EXT STDS 083',
            'FRENCH 110',
            'FRENCH 111',
            'FRENCH 203',
            'FRENCH 204',
            'FRENCH 301',
            'FRENCH 304',
            'FRENCH 331',
            'FRENCH 360',
            'GEOG 331',
            'GEOG 399',
            'GEOG 402',
            'GEOG 444',
            'GEOLOGY 360',
            'GEOLOGY 444',
            'GEOLOGY 560',
            'HISTORY 303',
            'HISTORY 312',
            'HISTORY 316',
            'HISTORY 333',
            'HISTORY 336',
            'HISTORY 350',
            'HISTORY 446',
            'HONORS 275',
            'HUMAN SV 235',
            'HUMAN SV 325',
            'HUMAN SV 375',
            'HUMAN SV 411',
            'HUMAN SV 420',
            'HUMAN SV 421',
            'INTRDSCP 350',
            'INTRDSCP 351',
            'INTRDSCP 399',
            'INTRDSCP 442',
            'INTRNTL 250',
            'INTRNTL 333',
            'JAPANESE 001',
            'JAPANESE 110',
            'JAPANESE 111',
            'JAPANESE 211',
            'JAPANESE 305',
            'JAPANESE 311',
            'JAPANESE 360',
            'JOURNAL 239',
            'JOURNAL 343',
            'JOURNAL 454',
            'KINESIOLOGY 446',
            'LIB STDS 200',
            'LIB STDS 202',
            'LIB STDS 301',
            'LIB STDS 307',
            'LIB STDS 311',
            'LIB STDS 331',
            'LIB STDS 336',
            'MATH 430',
            'MATH 490',
            'MATH 746',
            'MHR 375',
            'MUSIC 218',
            'NO COURSE ENROLLMENT',
            'NURSING 315',
            'NURSING 317',
            'NURSING 415',
            'NURSING 418',
            'NURSING 438',
            'NURSING 496',
            'NURSING 736',
            'NURSING 738',
            'PHILOSOPHY 105',
            'PHILOSOPHY 109',
            'PHILOSOPHY 426',
            'PHILOSOPHY 446',
            'PHY ED 208',
            'POLSCI 101',
            'POLSCI 212',
            'POLSCI 301',
            'POLSCI 303',
            'POLSCI 312',
            'POLSCI 372',
            'POLSCI 373',
            'POLSCI 374',
            'PROF COUNS 202',
            'PROF COUNS 724',
            'PSYCHOLOGY 225',
            'PSYCHOLOGY 275',
            'PSYCHOLOGY 446',
            'PSYCHOLOGY 480',
            'RELIGIOUS STUDIES 395',
            'RELIGIOUS STUDIES 399',
            'RTF 399',
            'SEC ED 202',
            'SEC ED 349',
            'SEC ED 377',
            'SEC ED 400',
            'SEC ED 401',
            'SEC ED 404',
            'SEC ED 405',
            'SEC ED 450',
            'SEC ED 451',
            'SEC ED 455',
            'SEC ED 460',
            'SEC ED 461',
            'SEC ED 465',
            'SEC ED 549',
            'SEC ED 577',
            'SOCIAL JUSTICE 399',
            'SOCIAL WORK 333',
            'SOCIAL WORK 410',
            'SPANISH 110',
            'SPANISH 111',
            'SPANISH 203',
            'SPANISH 204',
            'SPANISH 207',
            'SPANISH 208',
            'SPANISH 300',
            'SPANISH 301',
            'SPANISH 304',
            'SPANISH 308',
            'SPANISH 309',
            'SPANISH 310',
            'SPANISH 311',
            'SPANISH 312',
            'SPANISH 313',
            'SPANISH 314',
            'SPANISH 318',
            'SPANISH 320',
            'SPANISH 325',
            'SPANISH 332',
            'SPANISH 351',
            'SPANISH 361',
            'SPANISH 362',
            'SPANISH 363',
            'SPANISH 364',
            'SPANISH 365',
            'SPANISH 474',
            'SPEC ED 308',
            'SPEC ED 456',
            'SRVC CRS 421',
            'SRVC CRS 422',
            'SRVC CRS 621',
            'SRVC CRS 622',
            'THEATRE 202',
            'THEATRE 404',
            'THEATRE 463',
            'THEATRE 663',
            'TNHSL 521',
            'TNHSL 522',
            'WOMEN''S STUDIES 224',
            'WOMEN''S STUDIES 303',
            'WOMEN''S STUDIES 332',
            'WOMEN''S STUDIES 366',
            'WOMEN''S STUDIES 399',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    requirements_met = schema.Tuple(
        title=_(u'Requirements Met'),
        default=(
            'CS',
            'Culture (XC)',
            'Ethnic Studies (ES)',
            'Global C itizenship (GC)',
            'Global Scholar (GS)',
            'Honors',
            'Humanities (HU)',
            'Math (MA)',
            'Math (XM)',
            'Natural Science (NS)',
            'Nature (XN)',
            'Quest I',
            'Quest II',
            'Quest III',
            'Quest Speaking',
            'Quest Writing',
            'Social Science (SS)',
            'Society (XS)',
            'XK',
            'XL',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    course_enrollment_at = schema.Tuple(
        title=_(u'Course Enrollment at'),
        default=(
            'UW Oshkosh Only',
            'UW Oshkosh & Host (concurrent enrollment)',
            'Host Only',
            'No Course Enrollment',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    program_cycle = schema.Tuple(
        title=_(u'Program Cycle'),
        default=(
            'once',
            'annually',
            'every 2 years',
            'every 3 years',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    building = schema.Tuple(
        title=_(u'Building'),
        default=(
            'Albee Hall',
            'Alumni Welcome & Conference Center',
            'Arts and Communications Building',
            'Blackhawk Commons',
            'Center for Equity & Diversity',
            'Clow',
            'Dempsey',
            'ERIC',
            'Fredric March Theatre',
            'Gruenhagen Conference Center',
            'Halsey Science Center',
            'Harrington Hall',
            'Kolf',
            'Multicultural Education Center',
            'Nursing / Education Building',
            'Oviatt House',
            'Polk Library',
            'Pollock Alumni House',
            'Radford Hall',
            'Reeve Memorial Union',
            'Sage Hall',
            'Student Recreation and Wellness Center',
            'Student Success Center',
            'Swart Hall',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    transition_type = schema.Tuple(
        title=_(u'Transition Type'),
        default=(
            'Arrival in first host city',
            'Day trip',
            'Intercity transfer',
            'Arrival home',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    leadership_role = schema.Tuple(
        title=_(u'Leadership Role'),
        default=(
            'On-site Program Leader',
            'On-site Program Co-leader',
            'Individual external to the UW providing leadership support',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    title = schema.Tuple(
        title=_(u'Title'),
        default=(
            'Dr.',
            'Professor',
            'None',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    approving_as = schema.Tuple(
        title=_(u'Approving as'),
        default=(
            'Chair',
            'Dean',
            'Committee Chair',
            'USP Reviewer',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    class_standing = schema.Tuple(
        title=_(u'Class Standing'),
        default=(
            '0+ credits',
            '30+ credits',
            '60+ credits',
            '90+ credits',
            'post-graduate',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    compensation_type = schema.Tuple(
        title=_(u'Compensation Type'),
        default=(
            'Part of load',
            'Overload',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    compensation_payment_or_replacement = schema.Tuple(
        title=_(u'Compensation Payment or Replacement'),
        default=(
            'No replacement costs due to the College',
            'Replacement costs due to the College',
            'Paid by the College',
            'Paid by external partner',
            'Paid by study away students',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    percentage_or_lump_sum = schema.Tuple(
        title=_(u'Compensation Percentage or Lump Sum'),
        default=(
            '2.5% per credit (faculty rate)',
            '3.33% per credit (academic staff rate)',
            'Lump sum',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    equipment_and_space = schema.Tuple(
        title=_(u'Equipment & Space'),
        default=(
            'I do not need teaching space or equipment.',
            'I have the following space/equipment needs: (if checked, please describe).',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    guest_lectures = schema.Tuple(
        title=_(u'Guest Lectures'),
        default=(
            'I do not need guest lecturers.',
            'I do need guest lecturers and will include details within the daily itinerary in this application.',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )

    immigration_status = schema.Tuple(
        title=_(u'Immigration Status'),
        default=(
            'Green Card Holder (US Permanent Resident)',
            'A',
            'A-2',
            'B-1',
            'B-2',
            'BCC',
            'C',
            'C5',
            'CR1',
            'CR2',
            'CW-1',
            'D',
            'DV',
            'E',
            'E-3',
            'E1',
            'E2',
            'E3',
            'EW3',
            'F',
            'F1',
            'F2A',
            'F2B',
            'F3',
            'F4',
            'G1-G5, NATO',
            'H-1B',
            'H-1B1 - Chile',
            'H-1B1 - Singapore',
            'H-2A',
            'H-2B',
            'H-3',
            'I',
            'I5',
            'IH3',
            'IH4',
            'IR1',
            'IR2',
            'IR3',
            'IR4',
            'IR5',
            'J',
            'K-1',
            'K-3',
            'L',
            'M',
            'NATO1-6',
            'O',
            'P',
            'Q',
            'R',
            'R5',
            'S (many)',
            'SB',
            'SD',
            'SI',
            'SQ',
            'SR',
            'T',
            'T5',
            'TN/TD',
            'U',
            'V'
        ),
        missing_value=None,
        required=False,
        value_type=schema.TextLine()
    )

    eligibility_requirement = schema.Tuple(
        title=_(u'Eligibility Requirement'),
        default=(
            'Undergraduate students must have a minimum G.P.A. of 2.0, be in good standing, and meet course prerequisites. As part of the application process, your disciplinary file will be reviewed. If you have a campus disciplinary file, this will be taken into consideration when determining your eligibility. Undergraduates who do not meet minimum GPA and course requirements should contact the program leader prior to applying to determine course eligibility.',
            'Undergraduate students must have a minimum G.P.A. of 2.0, be in good standing, and meet course prerequisites. Undergraduate students who are required to complete a Quest III course to fulfill graduation requirements may apply. Students must have a minimum G.P.A. of 2.0, be in good standing, meet course prerequisites, and meet Quest III prerequisites. As part of the application process, your disciplinary file will be reviewed. If you have a campus disciplinary file, this will be taken into consideration when determining your eligibility. Undergraduates who are not required to complete a Quest III course to graduate are not eligible; however, they may apply for consideration on a space-available basis along with USP & instructor consent. Seats will be assigned to these applicants only after all applicants who are required to complete Quest III to graduate and who have met the STEP III deadline have been awarded a seat.',
            'Students must have a minimum G.P.A. of 3.25, be accepted into the Professional Counseling Graduate program, be in good standing, and meet course prerequisites. As part of the application process, your disciplinary file will be reviewed. If you have a campus disciplinary file, this will be taken into consideration when determining your eligibility. Undergraduates who do not meet minimum GPA and course requirements should contact the program leader prior to applying to determine course eligibility.',
        ),
        missing_value=None,
        required=False,
        value_type=schema.TextLine()
    )

    education_level = schema.Tuple(
        title=_(u'Education Levels'),
        default=(
            'High School Junior',
            'High School Senior',
            'University Freshman',
            'University Sophomore',
            'University Junior',
            'University Senior',
            'Graduate School',
        ),
        missing_value=None,
        required=True,
        value_type = schema.TextLine(),
    )

    student_status = schema.Tuple(
        title=_(u'Student Status'),
        default=(
            '1) UWO students making progress toward a degree may apply.',
            '2) UW System students making progress toward a degree may apply.',
            '3) Students making progress toward a degree at an institution of higher education may apply. (This includes exchange students and visiting students from abroad currently studying at UW Oshkosh.)',
            '4) Students making progress toward a degree at an institution of higher education and community members may apply.  Community members require approval by the Program Liaison."',
        ),
        missing_value=None,
        required=True,
        value_type = schema.TextLine(),
    )

    program_of_study = schema.Tuple(
        title=_(u'Program of Study'),
        default=(
            'Honors College',
            'College of Business',
            'College of Nursing',
            'MBA - Executive Path',
            'MBA - Professional Path',
        ),
        missing_value=None,
        required=True,
        value_type = schema.TextLine(),
    )

    enrollment_institution = schema.Tuple(
        title=_(u'Course Enrollment Institutions'),
        default=(
            'UW Oshkosh only',
            'Foreign Cooperating Partner only',
            'Simultaneous enrollment at UW Oshkosh and Foreign Cooperating Partner',
        ),
        missing_value=None,
        required=True,
        value_type = schema.TextLine(),
    )

    widget(state_of_wisconsin_need_based_travel_grant_form=NamedFileFieldWidget)
    state_of_wisconsin_need_based_travel_grant_form = schema.ASCII(
        title=u'State of Wisconsin Need-based Travel Grant Form',
        description=u'select the PDF for this form',
        required=False,
        missing_value=None,
        default=None,
    )
    widget(special_student_form_for_undergraduate_admissions=NamedFileFieldWidget)
    special_student_form_for_undergraduate_admissions = schema.ASCII(
        title=u'Special Student Form for Undergraduate Admissions',
        description=u'select the PDF for this form',
        required=False,
        missing_value=None,
        default=None,
    )
    widget(disciplinary_clearance_form=NamedFileFieldWidget)
    disciplinary_clearance_form = schema.ASCII(
        title=u'Disciplinary Clearance Form',
        description=u'select the PDF for this form',
        required=False,
        missing_value=None,
        default=None,
    )
    widget('uwo_logo', NamedImageFieldWidget)
    uwo_logo = schema.ASCII(
        title=_(u'UWO Logo'),
        description=_(u'will appear on program description view'),
        required=False,
        missing_value=None,
        default=None,
    )
    program_view_footer = schema.Text(
        title=_(u'Program Footer Text'),
        description=_(u'will appear at bottom of public program view'),
        required=False,
        missing_value=None,
        default=None,
    )
    airport_transfer = schema.Tuple(
        title=_(u'Airport Transfer Modes'),
        default=(
            'No US airport transfer provided',
            'School Bus',
            'Coach Bus',
        ),
        missing_value=None,
        required=True,
        value_type=schema.TextLine()
    )



class OIEStudyAbroadStudentControlPanelForm(RegistryEditForm):
    schema = IOIEStudyAbroadStudentControlPanel
    schema_prefix = "oiestudyabroadstudent"
    label = u'OIE Study Abroad Settings'


OIEStudyAbroadStudentControlPanelView = layout.wrap_form(
    OIEStudyAbroadStudentControlPanelForm, ControlPanelFormWrapper)
